//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    public partial class Book : object
    {
        
        private string IdField;
        
        private string TitleField;
        
        private string CategoryField;
        
        private string LangField;
        
        private int PagesField;
        
        private int AgeLimitField;
        
        private LibraryServiceReference.Author[] AuthorsField;
        
        private int PublicationDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Category
        {
            get
            {
                return this.CategoryField;
            }
            set
            {
                this.CategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Pages
        {
            get
            {
                return this.PagesField;
            }
            set
            {
                this.PagesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int AgeLimit
        {
            get
            {
                return this.AgeLimitField;
            }
            set
            {
                this.AgeLimitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public LibraryServiceReference.Author[] Authors
        {
            get
            {
                return this.AuthorsField;
            }
            set
            {
                this.AuthorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int PublicationDate
        {
            get
            {
                return this.PublicationDateField;
            }
            set
            {
                this.PublicationDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://tempuri.org/")]
    public partial class Author : object
    {
        
        private string NameField;
        
        private string LangField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Lang
        {
            get
            {
                return this.LangField;
            }
            set
            {
                this.LangField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibraryServiceReference.LibraryWebServiceSoap")]
    public interface LibraryWebServiceSoap
    {
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        LibraryServiceReference.AddResponse Add(LibraryServiceReference.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.AddResponse> AddAsync(LibraryServiceReference.AddRequest request);
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        LibraryServiceReference.DeleteResponse Delete(LibraryServiceReference.DeleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Delete", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.DeleteResponse> DeleteAsync(LibraryServiceReference.DeleteRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        LibraryServiceReference.GetAllResponse GetAll(LibraryServiceReference.GetAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAll", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetAllResponse> GetAllAsync(LibraryServiceReference.GetAllRequest request);
        
        // CODEGEN: Generating message contract since element name authorName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooksByAuthor", ReplyAction="*")]
        LibraryServiceReference.GetBooksByAuthorResponse GetBooksByAuthor(LibraryServiceReference.GetBooksByAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooksByAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByAuthorResponse> GetBooksByAuthorAsync(LibraryServiceReference.GetBooksByAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooksByCategory", ReplyAction="*")]
        LibraryServiceReference.GetBooksByCategoryResponse GetBooksByCategory(LibraryServiceReference.GetBooksByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooksByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByCategoryResponse> GetBooksByCategoryAsync(LibraryServiceReference.GetBooksByCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        LibraryServiceReference.GetByIdResponse GetById(LibraryServiceReference.GetByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetById", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByIdResponse> GetByIdAsync(LibraryServiceReference.GetByIdRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooksByTitle", ReplyAction="*")]
        LibraryServiceReference.GetBooksByTitleResponse GetBooksByTitle(LibraryServiceReference.GetBooksByTitleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBooksByTitle", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByTitleResponse> GetBooksByTitleAsync(LibraryServiceReference.GetBooksByTitleRequest request);
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        LibraryServiceReference.UpdateResponse Update(LibraryServiceReference.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<LibraryServiceReference.UpdateResponse> UpdateAsync(LibraryServiceReference.UpdateRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.AddRequestBody Body;
        
        public AddRequest()
        {
        }
        
        public AddRequest(LibraryServiceReference.AddRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book book;
        
        public AddRequestBody()
        {
        }
        
        public AddRequestBody(LibraryServiceReference.Book book)
        {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.AddResponseBody Body;
        
        public AddResponse()
        {
        }
        
        public AddResponse(LibraryServiceReference.AddResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody()
        {
        }
        
        public AddResponseBody(int AddResult)
        {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Delete", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.DeleteRequestBody Body;
        
        public DeleteRequest()
        {
        }
        
        public DeleteRequest(LibraryServiceReference.DeleteRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book book;
        
        public DeleteRequestBody()
        {
        }
        
        public DeleteRequestBody(LibraryServiceReference.Book book)
        {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.DeleteResponseBody Body;
        
        public DeleteResponse()
        {
        }
        
        public DeleteResponse(LibraryServiceReference.DeleteResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DeleteResult;
        
        public DeleteResponseBody()
        {
        }
        
        public DeleteResponseBody(int DeleteResult)
        {
            this.DeleteResult = DeleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAll", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetAllRequestBody Body;
        
        public GetAllRequest()
        {
        }
        
        public GetAllRequest(LibraryServiceReference.GetAllRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRequestBody
    {
        
        public GetAllRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetAllResponseBody Body;
        
        public GetAllResponse()
        {
        }
        
        public GetAllResponse(LibraryServiceReference.GetAllResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetAllResult;
        
        public GetAllResponseBody()
        {
        }
        
        public GetAllResponseBody(LibraryServiceReference.Book[] GetAllResult)
        {
            this.GetAllResult = GetAllResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksByAuthorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksByAuthor", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetBooksByAuthorRequestBody Body;
        
        public GetBooksByAuthorRequest()
        {
        }
        
        public GetBooksByAuthorRequest(LibraryServiceReference.GetBooksByAuthorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksByAuthorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorName;
        
        public GetBooksByAuthorRequestBody()
        {
        }
        
        public GetBooksByAuthorRequestBody(string authorName)
        {
            this.authorName = authorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksByAuthorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksByAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetBooksByAuthorResponseBody Body;
        
        public GetBooksByAuthorResponse()
        {
        }
        
        public GetBooksByAuthorResponse(LibraryServiceReference.GetBooksByAuthorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksByAuthorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetBooksByAuthorResult;
        
        public GetBooksByAuthorResponseBody()
        {
        }
        
        public GetBooksByAuthorResponseBody(LibraryServiceReference.Book[] GetBooksByAuthorResult)
        {
            this.GetBooksByAuthorResult = GetBooksByAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksByCategoryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksByCategory", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetBooksByCategoryRequestBody Body;
        
        public GetBooksByCategoryRequest()
        {
        }
        
        public GetBooksByCategoryRequest(LibraryServiceReference.GetBooksByCategoryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksByCategoryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public GetBooksByCategoryRequestBody()
        {
        }
        
        public GetBooksByCategoryRequestBody(string category)
        {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksByCategoryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksByCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetBooksByCategoryResponseBody Body;
        
        public GetBooksByCategoryResponse()
        {
        }
        
        public GetBooksByCategoryResponse(LibraryServiceReference.GetBooksByCategoryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksByCategoryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetBooksByCategoryResult;
        
        public GetBooksByCategoryResponseBody()
        {
        }
        
        public GetBooksByCategoryResponseBody(LibraryServiceReference.Book[] GetBooksByCategoryResult)
        {
            this.GetBooksByCategoryResult = GetBooksByCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetById", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByIdRequestBody Body;
        
        public GetByIdRequest()
        {
        }
        
        public GetByIdRequest(LibraryServiceReference.GetByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetByIdRequestBody()
        {
        }
        
        public GetByIdRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetByIdResponseBody Body;
        
        public GetByIdResponse()
        {
        }
        
        public GetByIdResponse(LibraryServiceReference.GetByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book GetByIdResult;
        
        public GetByIdResponseBody()
        {
        }
        
        public GetByIdResponseBody(LibraryServiceReference.Book GetByIdResult)
        {
            this.GetByIdResult = GetByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksByTitleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksByTitle", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetBooksByTitleRequestBody Body;
        
        public GetBooksByTitleRequest()
        {
        }
        
        public GetBooksByTitleRequest(LibraryServiceReference.GetBooksByTitleRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksByTitleRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public GetBooksByTitleRequestBody()
        {
        }
        
        public GetBooksByTitleRequestBody(string title)
        {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBooksByTitleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBooksByTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.GetBooksByTitleResponseBody Body;
        
        public GetBooksByTitleResponse()
        {
        }
        
        public GetBooksByTitleResponse(LibraryServiceReference.GetBooksByTitleResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBooksByTitleResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book[] GetBooksByTitleResult;
        
        public GetBooksByTitleResponseBody()
        {
        }
        
        public GetBooksByTitleResponseBody(LibraryServiceReference.Book[] GetBooksByTitleResult)
        {
            this.GetBooksByTitleResult = GetBooksByTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.UpdateRequestBody Body;
        
        public UpdateRequest()
        {
        }
        
        public UpdateRequest(LibraryServiceReference.UpdateRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public LibraryServiceReference.Book book;
        
        public UpdateRequestBody()
        {
        }
        
        public UpdateRequestBody(LibraryServiceReference.Book book)
        {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public LibraryServiceReference.UpdateResponseBody Body;
        
        public UpdateResponse()
        {
        }
        
        public UpdateResponse(LibraryServiceReference.UpdateResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody()
        {
        }
        
        public UpdateResponseBody(int UpdateResult)
        {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface LibraryWebServiceSoapChannel : LibraryServiceReference.LibraryWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class LibraryWebServiceSoapClient : System.ServiceModel.ClientBase<LibraryServiceReference.LibraryWebServiceSoap>, LibraryServiceReference.LibraryWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), LibraryWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(LibraryWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public LibraryWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.AddResponse LibraryServiceReference.LibraryWebServiceSoap.Add(LibraryServiceReference.AddRequest request)
        {
            return base.Channel.Add(request);
        }
        
        public int Add(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.AddRequest inValue = new LibraryServiceReference.AddRequest();
            inValue.Body = new LibraryServiceReference.AddRequestBody();
            inValue.Body.book = book;
            LibraryServiceReference.AddResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.AddResponse> LibraryServiceReference.LibraryWebServiceSoap.AddAsync(LibraryServiceReference.AddRequest request)
        {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.AddResponse> AddAsync(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.AddRequest inValue = new LibraryServiceReference.AddRequest();
            inValue.Body = new LibraryServiceReference.AddRequestBody();
            inValue.Body.book = book;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.DeleteResponse LibraryServiceReference.LibraryWebServiceSoap.Delete(LibraryServiceReference.DeleteRequest request)
        {
            return base.Channel.Delete(request);
        }
        
        public int Delete(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.DeleteRequest inValue = new LibraryServiceReference.DeleteRequest();
            inValue.Body = new LibraryServiceReference.DeleteRequestBody();
            inValue.Body.book = book;
            LibraryServiceReference.DeleteResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).Delete(inValue);
            return retVal.Body.DeleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.DeleteResponse> LibraryServiceReference.LibraryWebServiceSoap.DeleteAsync(LibraryServiceReference.DeleteRequest request)
        {
            return base.Channel.DeleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.DeleteResponse> DeleteAsync(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.DeleteRequest inValue = new LibraryServiceReference.DeleteRequest();
            inValue.Body = new LibraryServiceReference.DeleteRequestBody();
            inValue.Body.book = book;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).DeleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetAllResponse LibraryServiceReference.LibraryWebServiceSoap.GetAll(LibraryServiceReference.GetAllRequest request)
        {
            return base.Channel.GetAll(request);
        }
        
        public LibraryServiceReference.Book[] GetAll()
        {
            LibraryServiceReference.GetAllRequest inValue = new LibraryServiceReference.GetAllRequest();
            inValue.Body = new LibraryServiceReference.GetAllRequestBody();
            LibraryServiceReference.GetAllResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetAll(inValue);
            return retVal.Body.GetAllResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetAllResponse> LibraryServiceReference.LibraryWebServiceSoap.GetAllAsync(LibraryServiceReference.GetAllRequest request)
        {
            return base.Channel.GetAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetAllResponse> GetAllAsync()
        {
            LibraryServiceReference.GetAllRequest inValue = new LibraryServiceReference.GetAllRequest();
            inValue.Body = new LibraryServiceReference.GetAllRequestBody();
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetBooksByAuthorResponse LibraryServiceReference.LibraryWebServiceSoap.GetBooksByAuthor(LibraryServiceReference.GetBooksByAuthorRequest request)
        {
            return base.Channel.GetBooksByAuthor(request);
        }
        
        public LibraryServiceReference.Book[] GetBooksByAuthor(string authorName)
        {
            LibraryServiceReference.GetBooksByAuthorRequest inValue = new LibraryServiceReference.GetBooksByAuthorRequest();
            inValue.Body = new LibraryServiceReference.GetBooksByAuthorRequestBody();
            inValue.Body.authorName = authorName;
            LibraryServiceReference.GetBooksByAuthorResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetBooksByAuthor(inValue);
            return retVal.Body.GetBooksByAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByAuthorResponse> LibraryServiceReference.LibraryWebServiceSoap.GetBooksByAuthorAsync(LibraryServiceReference.GetBooksByAuthorRequest request)
        {
            return base.Channel.GetBooksByAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByAuthorResponse> GetBooksByAuthorAsync(string authorName)
        {
            LibraryServiceReference.GetBooksByAuthorRequest inValue = new LibraryServiceReference.GetBooksByAuthorRequest();
            inValue.Body = new LibraryServiceReference.GetBooksByAuthorRequestBody();
            inValue.Body.authorName = authorName;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetBooksByAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetBooksByCategoryResponse LibraryServiceReference.LibraryWebServiceSoap.GetBooksByCategory(LibraryServiceReference.GetBooksByCategoryRequest request)
        {
            return base.Channel.GetBooksByCategory(request);
        }
        
        public LibraryServiceReference.Book[] GetBooksByCategory(string category)
        {
            LibraryServiceReference.GetBooksByCategoryRequest inValue = new LibraryServiceReference.GetBooksByCategoryRequest();
            inValue.Body = new LibraryServiceReference.GetBooksByCategoryRequestBody();
            inValue.Body.category = category;
            LibraryServiceReference.GetBooksByCategoryResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetBooksByCategory(inValue);
            return retVal.Body.GetBooksByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByCategoryResponse> LibraryServiceReference.LibraryWebServiceSoap.GetBooksByCategoryAsync(LibraryServiceReference.GetBooksByCategoryRequest request)
        {
            return base.Channel.GetBooksByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByCategoryResponse> GetBooksByCategoryAsync(string category)
        {
            LibraryServiceReference.GetBooksByCategoryRequest inValue = new LibraryServiceReference.GetBooksByCategoryRequest();
            inValue.Body = new LibraryServiceReference.GetBooksByCategoryRequestBody();
            inValue.Body.category = category;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetBooksByCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetByIdResponse LibraryServiceReference.LibraryWebServiceSoap.GetById(LibraryServiceReference.GetByIdRequest request)
        {
            return base.Channel.GetById(request);
        }
        
        public LibraryServiceReference.Book GetById(string id)
        {
            LibraryServiceReference.GetByIdRequest inValue = new LibraryServiceReference.GetByIdRequest();
            inValue.Body = new LibraryServiceReference.GetByIdRequestBody();
            inValue.Body.id = id;
            LibraryServiceReference.GetByIdResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetById(inValue);
            return retVal.Body.GetByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetByIdResponse> LibraryServiceReference.LibraryWebServiceSoap.GetByIdAsync(LibraryServiceReference.GetByIdRequest request)
        {
            return base.Channel.GetByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetByIdResponse> GetByIdAsync(string id)
        {
            LibraryServiceReference.GetByIdRequest inValue = new LibraryServiceReference.GetByIdRequest();
            inValue.Body = new LibraryServiceReference.GetByIdRequestBody();
            inValue.Body.id = id;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.GetBooksByTitleResponse LibraryServiceReference.LibraryWebServiceSoap.GetBooksByTitle(LibraryServiceReference.GetBooksByTitleRequest request)
        {
            return base.Channel.GetBooksByTitle(request);
        }
        
        public LibraryServiceReference.Book[] GetBooksByTitle(string title)
        {
            LibraryServiceReference.GetBooksByTitleRequest inValue = new LibraryServiceReference.GetBooksByTitleRequest();
            inValue.Body = new LibraryServiceReference.GetBooksByTitleRequestBody();
            inValue.Body.title = title;
            LibraryServiceReference.GetBooksByTitleResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetBooksByTitle(inValue);
            return retVal.Body.GetBooksByTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByTitleResponse> LibraryServiceReference.LibraryWebServiceSoap.GetBooksByTitleAsync(LibraryServiceReference.GetBooksByTitleRequest request)
        {
            return base.Channel.GetBooksByTitleAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.GetBooksByTitleResponse> GetBooksByTitleAsync(string title)
        {
            LibraryServiceReference.GetBooksByTitleRequest inValue = new LibraryServiceReference.GetBooksByTitleRequest();
            inValue.Body = new LibraryServiceReference.GetBooksByTitleRequestBody();
            inValue.Body.title = title;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).GetBooksByTitleAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LibraryServiceReference.UpdateResponse LibraryServiceReference.LibraryWebServiceSoap.Update(LibraryServiceReference.UpdateRequest request)
        {
            return base.Channel.Update(request);
        }
        
        public int Update(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.UpdateRequest inValue = new LibraryServiceReference.UpdateRequest();
            inValue.Body = new LibraryServiceReference.UpdateRequestBody();
            inValue.Body.book = book;
            LibraryServiceReference.UpdateResponse retVal = ((LibraryServiceReference.LibraryWebServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<LibraryServiceReference.UpdateResponse> LibraryServiceReference.LibraryWebServiceSoap.UpdateAsync(LibraryServiceReference.UpdateRequest request)
        {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<LibraryServiceReference.UpdateResponse> UpdateAsync(LibraryServiceReference.Book book)
        {
            LibraryServiceReference.UpdateRequest inValue = new LibraryServiceReference.UpdateRequest();
            inValue.Body = new LibraryServiceReference.UpdateRequestBody();
            inValue.Body.book = book;
            return ((LibraryServiceReference.LibraryWebServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:44337/LibraryWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.LibraryWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:44337/LibraryWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            LibraryWebServiceSoap,
            
            LibraryWebServiceSoap12,
        }
    }
}
